### PR TITLE
Add cors to API

### PR DESCRIPTION
**Pull request by ericgio**
CORS is on by default. This allows us to control it, especially in dev environments when it makes sense to allow all browser requests.

### CODE REVIEW

**Comment by makinde** [comment]
I'm curious, what's the bug/[security] issue this aims to address?

**Comment by ericgio** [comment]
By default, browsers aren't allowed to make cross-origin requests ([read more about Cross-Origin Resource Sharing, or CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)). This means that a web client with a different origin than that of the API won't be able to make requests unless the API allows it to do so.

Short term, this primarily means that a web client can't make client-side requests in development, since the web client and API run on different ports and are therefore different origins. In prod, we'd be likely to serve the API and web client from the same domain (www.yekrojam.com accessing api.yekrojam.com), so it wouldn't be an issue. Simplest solution therefore is to make sharing open in development and restricted in production, which is what I'm doing here.

Longer-term, the API will need to whitelist which domains are allowed to access it since we'd conceivably have self-hosted one-off versions that are cross-domain (eg: org.designerfund.com accessing api.yekrojam.com).

Either way, the cors module will allow us to control cross-origin access to the API.

**Comment by makinde** [comment]
I'm not sure this does what you want it to. If you set the origin field to `false`, it will want to domains to match exactly, and that includes subdomains. So www.yerkrojam.com won't be able to read a response from api..yekrojam.com.

That said, from a security standpoint, I think it's actually fine to allow any cross origin requests. The way the jwt is delivered, that should adequately protect from requests we don't want.

This should be able to come down to `cors({ origin: true }),`

I'm guessing we may need to discuss this in person :)

**Comment by makinde** [comment]
BTW, do you have cors turn on for the version of the API that you're hitting now? i assume so since the ports don't match.

**Comment by ericgio** [comment]
> I think it's actually fine to allow any cross origin requests

Sure, that works. Will update the PR.

> do you have cors turn on for the version of the API that you're hitting now

Yes, I was hitting various API branches where I had enabled cors. Doesn't work with master.

**Comment by makinde** [comment]
Last tweak...all module versions are exact. Came across this [Heroku best practice](https://devcenter.heroku.com/articles/node-best-practices#use-a-smart-npmrc). It's a little old, but it makes sense to me to lock versions and only update them when we explicitly want to.

**Pull request merged**
