### PR TITLE
Adding models as a thing that can be imported.

### PR DESCRIPTION
**Pull request by makinde**
I might use this later for some async jobs or server side stuff.

### CODE REVIEW

**Comment by ericgio** [comment]
I never quite understood the need for this when we were doing it in Majorkey. Async jobs should be able to call the API normally like any other client right? Also what is "server-side stuff?" :)

**Comment by makinde** [comment]
Yeah, they can call the API, just some extra security work to set up doing it that way.

The server side stuff is this. As the structure of the API comes together, one of the things I want to tinker with it markojs. I'm thinking of setting that up to do most rendering serverside and do data fetching on the server directly through the models. Then the web pages can do writes from the client via API calls. Probably lots of gotchas in there, but I wanna see if that's an effective approach.

**Comment by ericgio** [comment]
Not sure how you're thinking about authorization, but I would think a lot of that logic will live in the endpoints and not the models themselves. If that's the case, then exporting the models allows consumers to bypass all that auth logic, which seems dangerous.

**Comment by makinde** [comment]
Yes and no. I'm implementing the authorization using `mongoose-authz`, which defines the authorization rules as a schema extension. The way the API is set up, 0 critical logic lives in the `express-restify-mongoose` layer. It's all baked into the modem that you query/get back from mongoose.

Yes, if someone imports the API models, they can bypass authz checks by seeing a specific field. This isn't super straight forward to explain here, but this is a case I've considered and I'm confident is not an issue. I can explain in more detail live.

**Comment by ericgio** [comment]
Yeah, I'd love to hear more about how you're implementing the auth piece so I can understand it better.

**Comment by ericgio** [comment]
I was pretty skeptical about breaking the models out like this, but I now wonder if it would make sense to take it to the extreme and completely split the data storage layer (DB/ORM/Models) from the API (basically just what's in the `/v1` and `/v2` folders). That would could allow flexibility in how the data is exposed (eg: GraphQL instead of REST) while keeping the underlying structure the same.

**Comment by makinde** [comment]
Yeah, that can be done, and that's what I've had in mind with the project structure. The simplest way to add graphQL would be to add it in a `/v3` folder and have it access the models right there.

Funny enough, I recently realized that I didn't need the models exported like that do to the short circuiting that I wanted to do in `/mtweb`, so I was about to delete the file that exports them. I'm fine to leave them if you wanted to create another repo for graphQL and use them. Or we can do graphQL in this same codebase and have it happen alongside everything else.

**Comment by ericgio** [comment]
Whatever makes the most sense to you. I was originally thinking they'd be totally separate things to avoid mucking up what you currently have in the API, but adding a v3 folder is certainly a simpler solution.

**Comment by makinde** [comment]
I'm guessing some of the middleware and utils will be shared. The stuff that takes in raw stuff from the `req` and transforms it into options for mongoose. You should go ahead and give it a shot. The basic approach/set up for the code is:
- If it comes from the request, and needs to be shared across graphQL and ResourceJS, put it in express middleware.
- If it has to do with logic that should happen on both graphQL and ResourceJS actions, try to push it down into the models
- Otherwise, the graphQL/ResourceJS layers should be as thin as possible and only do the stuff that's specific to those technologies. The less code in those layers, the more that's shared.

**Comment by ericgio** [comment]
Actually things might be a little more messy since it would be a separate app/server.

**Comment by makinde** [comment]
Can you explain a bit more what that means? Would it be bad to have a server running that allowed access via /v2 for REST and /v3 for graphQL?

**Comment by makinde** [comment]
I see. Yeah, you could def go either way on this. FWIW, you could do this at the end of `/v3/index.js` with the GraphQLServer you've created. You can access the underlying express object via `server.express`, outlined [here](https://github.com/prisma/graphql-yoga#how-to-eject-from-the-standard-express-setup). This is almost exactly the same as what happens at the end of `/v2/index.js`.

```js
const app = express();
app.use('/v2', myGraphQLServer.express);

module.exports = app;
```

If you do decide to do another repo, it'll prob make sense for me to start using version numbers in the `package.json` file of `@majorkey2/api` so that you don't accidentally get breaking changes.

**Pull request merged**
