### PR TITLE
Check for JWTs in production

### PR DESCRIPTION
**Pull request by ericgio**
With this change, the API will look for a valid json web token in every request. If it isn't there or it's invalid (expired, wrong secret, etc.), the request is rejected.

### CODE REVIEW

**Comment by ericgio** [comment]
Every client request now needs to include the token in the request header:

```js
fetch(`${process.env.API_URL}/${path}`, {
  headers: {
    Accept: 'application/json',
    'Accept-Encoding': 'gzip',
    Authorization: `Bearer ${authToken}`, // <--- This is what the server looks for
    'Content-Type': 'application/json; charset=utf-8',
  },
  ...options,
})
```

Here's how the client generates the token:
```js
import jwt from 'jsonwebtoken';

jwt.sign(payload, process.env.JWT_SECRET, {
  expiresIn: '1h',
  ...options,
});
```

where `payload` is an object with user info, if available (eg: `{ id }`), and `process.env.JWT_SECRET` matches what's on the server.

**Comment by ericgio** [comment]
Something I didn't include here is how the API accesses the object to check permissions. I think it just becomes available on the request object, so we could add a check in the restify hooks.

**Comment by makinde** [comment]
Oh snap, I totally missed this. Sweet.

Only question is this line:
>   `credentialsRequired: process.env.NODE_ENV === 'production',`

Any reason to either (a) not require the token (and just assume the person is logged out if there's no token, which is the same as getting an empty token?) or (b) requiring it in dev as well? It'd be nice to have the functionality match between this and production. I can see writing some code that doesn't correctly generate/specify the token, and it would seem to work locally, then break in prod.

**Comment by ericgio** [comment]
> not require the token (and just assume the person is logged out if there's no token, which is the same as getting an empty token?

Those are not the same as I understand it. An empty token means the client making the request has access to the API and but there is no user session (valid request). No token means the client making the request does not have access to the API at all (request would be rejected).

> requiring it in dev as well? It'd be nice to have the functionality match between this and production

My thinking in general is that dev doesn't need all the security since it's not publicly accessible. It's also potentially annoying to have to change a bunch of restrictive settings to make development easier. 
 If a developer wants a prod-like environment, they simply need to change `process.env.NODE_ENV` to be `'production'`. Otherwise, it's a dev environment. That seems pretty straightforward to me.

> I can see writing some code that doesn't correctly generate/specify the token, and it would seem to work locally, then break in prod

Are there other ways to test for that? Feels like the client would need an integration test with the API in that case. One way we might improve things is for the code to be:

```js
credentialsRequired: process.env.NODE_ENV !== 'development',
```

That way, they'd be required in test environments as well.

**Comment by makinde** [comment]
I see. I think there are 3 cases for the token, and we're slotting them into 2 groups differently, with different intentions. The cases are:

1. There is no token (so the request isn't valid at all)
2. There is a token, but it's empty (meaning the request is from our client, but no one is logged in)
3. There is a token, and it has an id (meaning someone is logged in and making a valid request)

As you're describing it, I take it that you are grouping together case 2 & 3, and noting that they should be treated differently than 1. I think that mainly looks at the token as a way to tell if the request is from a valid source as a security measure.

I'm looking at it from a different direction. I group 1 & 2 together, and view them as different from 3. The API will soon start applying a lot of permissions based on the acting user. For the sake of those permissions, there's either a a logged-in user who can do things based on their associations, or acting party is a complete stranger and will be pretty restricted. This view assumes that since it's easy to get a valid, empty token (just hit a landing page), that there's little added security by requiring that an empty token is there.

The analogous thing here to me is how auth works on MK. We wouldn't turn slack auth off in dev to make development easier. We made slack auth work in dev so it was the same environment.

It's also unclear what gets harder to do in dev if `credentialsRequired` is `true`.

**Comment by makinde** [comment]
Oic, you are also using the `jwt` to guard against CSRF attacks.

**Comment by makinde** [comment]
A few things in my mind:
- This def works for the way you have the jet set up in your client.
- Id love to understand what gets harder in development of the jet is forced to be there. Authentication and CRSF protection are both things that have been enabled in dev environments before.
- I've been thinking about an alternative method of storing the jwt in a cookie and doin a csrf check. Doesn't need to block this, and both can coexist, just providing context on what's in my head.
- Are you storing the jwt in local storage on the client?

**Comment by ericgio** [comment]
Maybe another way to think about it is:

1. External Access & Security
2. Internal Access (User Permissions)

Where 2 & 3 above are 2a and 2b for me. I think possibly the confusing piece is that the JWT is blurring the relationship by both validating API access as well as delivering the user data needed to check permissions.

> noting that they should be treated differently than 1

I'm not sure if anything needs to be treated differently or that there's any action to take here. Maybe we're just trying to arrive at a common understanding of the system?

> there's either a logged-in user who can do things based on their associations, or acting party is a complete stranger and will be pretty restricted

Those are just levels of user permissions right? Logged-in vs. logged-out is the clearest delineation, but even with a logged in user you're checking for permissions, eg: whether they can mutate a record, access an admin page, etc.

**Comment by ericgio** [comment]
> Id love to understand what gets harder in development of the jet is forced to be there. Authentication and CRSF protection are both things that have been enabled in dev environments before.

It's beside the point. The token is about external security, which isn't necessary for a local dev environment. If you want to test a prod environment, change `NODE_ENV` in one place, don't sprinkle settings all over the place.

> I've been thinking about an alternative method of storing the jwt in a cookie and doin a csrf check. Doesn't need to block this, and both can coexist, just providing context on what's in my head. Are you storing the jwt in local storage on the client?

I'm storing it in the passport session, which I believe is in a cookie. Seems like what you're thinking about is basically the same thing? I'm not sure how a CSRF token relates to a JWT token; they seem to serve similar purposes.

**Comment by ericgio** [comment]
> This def works for the way you have the jwt set up in your client

Is there some specific piece of the client implementation you're concerned about? As I understand it, JWTs need to be included in every request header, so ultimately every client would need to do that.

**Comment by makinde** [comment]
Yeah, I think we have a shared model now. 1, 2a, and 2b. And yeah, you're currently using the `jwt` for both purposed.

>It's beside the point. The token is about external security, which isn't necessary for a local dev environment. If you want to test a prod environment, change NODE_ENV in one place, don't sprinkle settings all over the place.

Interesting. I'm actually not suggesting to have more settings. I'm suggesting to not even vary the behavior between `development` and `production` here. In effect, just deleting that line. The upside is that dev and prod will work the same way. I'm not sure what the downside is.

The #1 you list (External Access & Security) is what CSRF checks have traditionally handled. And those are on in dev. My mental framework is to only except things from dev if it (a) isn't possible to implement in dev (e.g. HTTPS) or makes development harder (e.g. aggressive package bundling). Outside of that, adding `process.env.NODE_ENV == 'production'` in places is sprinkling extra env specific config around, when doesn't seem to provide any upside.

> Is there some specific piece of the client implementation you're concerned about?

This implementation is totally fine to start with, but only accounts for one way of delivering a token. If the token is [stored in the cookie](https://auth0.com/docs/security/store-tokens), this code won't work. Again, that's fine for now, and I'll follow up with another diff with another code path.

**Comment by makinde** [comment]
To be clear, the change I'm suggesting is removing line 30 in `index.js`

**Comment by makinde** [comment]
Never mind my idea about also supporting the cookie. It's a little too tangled to support that approach

**Comment by makinde** [comment]
I think there are a few things that you're rolling together. The CORS case
you mention makes sense to me, and fits into what I said before. That's
something that just fundamentally works differently in development. Sure,
gate that with the NODE_ENV check.

The case of requiring the jwt is quite different. That request you're doing
from the browser will be completely invalid. Because the API will start
using the user id from the jwt and apply visibility rules and permissions
to what it returns. So for a GET like that, it'll just return an empty
list. For post requests, it generally will return an error. Which is the
correct behavior, both in prod and dev. Again, I'm not saying to sprinkle
around settings or to manually circumvent these things, because the code
will be behaving incorrectly if you do. Even apart from the API enforcing
permissions, there's code downstream that should be able to assume certain
info is there. The fact is that the API now requires more information to
come at it, and that's true in prod and dev.

There are some tools you can look into that'll help shape your requests.
I've been using Postman, which is pretty good at saving state. You could
also use the console in your browser as well. That's probably the easiest.

I mean, you do it this way for now, or manually change your code. But
again, it'll stop working for you once the authorization layer starts
enforcing what can happen on requests.

>  you need to deliver the token to the API via the request header
<https://github.com/yekrojam/api/pull/25#issuecomment-425621589>

Not quite. The `express-bearer-token` module provides 3 locations that the
token can live in the request. The auth0 guide specifies that you can
_store_ the jwt in a cookie, and then talks through how it will be
delivered via the cookie and how to mitigate the risks that introduces.
Either way, this doesn't matter much anymore since I've changed how I plan
to send

**Comment by ericgio** [comment]
Let's continue this discussion offline :)

As far as the PR, it's meant to be a reference, so feel free to explore other options and implement as desired.

**Comment by makinde** [comment]
Sounds good. 

I'm in a spot where stacked diffs would probably be helpful. This is actually the first chunk of work needed to bring the authorization layer to life. I've got another diff that does basically this. Instead of landing that, I'll create a branch/PR that will progressively layer commits so that when it's ready to land, this jwt stuff can go in at the same time as the actual authorization stuff. 

That'll give you as as long as possible to enjoy life without the authorization layer. In the mean time, given what you know about it (what I said above), perhaps we can brainstorm about the best way for you to be able to develop and poke at the API.

**Comment by makinde** [comment]
Circling back. I expect the first commit on #38 to replace this. You can see the specific commit here: https://github.com/yekrojam/api/pull/38/commits/a487cfd3ff7e4ca0791dca34ae4236f971d529f0

The balance it strikes is allowing (in dev) a auth token payload to be specific in plain text in the query param in dev (and that basically gets dumped in as `req.user`). The hope is that it makes it really easy to test from the browser, while also still forcing there to always be some information about who the acting user is (even if that's {}). So production and development run virtually the same code paths.

**Pull request closed without merging**
