### PR TITLE
Using Joi to enforce schema on environment

### PR DESCRIPTION
**Pull request by makinde**
This gives us much richer ways of specifying the environment variables that we need (beyond dotenv-safe's binary required or not). Should reduce issues of something not being available and make it slightly easier to make sure your dev app has everything.

### CODE REVIEW

**Comment by makinde** [comment]
I think I got 'em :P Lmk if I missed anything

**Comment by ericgio** [comment]
FYI, ran into issues where the `MONGODB_URI` validation was failing because the embedded password had an invalid character (specifically `^`). Fixed the issue by changing the password, but this might come back to bite us.

**Comment by makinde** [comment]
Doh. Is it that the auto-generated password the mLab made for you on heroku had a `^` character in it?

**Comment by ericgio** [comment]
Generated pw from LastPass (I set up a non-Heroku linked account), but yeah. We may never run into this issue again, but just wanted to call it out here for posterity.

**Pull request merged**
