### PR TITLE
Use yarn instead of npm

### PR DESCRIPTION
**Pull request by ericgio**
Yarn is faster/better. I don't trust those npm clowns...

### CODE REVIEW

**Comment by makinde** [comment]
Haha, this was a conscious choice. npm is getting better really quickly, and is in many ways ahead of yarn now. `npm audit` in [npm 6](https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905) is really nice, and I think a lot of the defaults are now like yarn (defaulting to a a lockfile and related things).

**Comment by ericgio** [comment]
Ah ok, seems like you're more up to date on this stuff than I am. I'd be interested to hear more about what you've read/heard. I guess I don't feel that strongly, assuming they're on par. I definitely trust FB as an engineering org way more than NPM though, that wasn't a joke. In any case, we should probably use the same tools in both the web and API repos.

**Comment by ericgio** [comment]
One annoying thing I've noticed about NPM is that it doesn't enforce the lockfile as well as Yarn. It's pretty easy to add dependencies with NPM and accidentally commit changes with an out of date lock file, whereas Yarn is much better about telling you that something's out of sync.

**Comment by makinde** [comment]
What's the workflow you're referencing? Is it

```
[manually edit package.json...]
git add .
git commit -m "foo"
```

and yarn will warn you in that case but npm won't?

**Comment by ericgio** [comment]
I'd have to be more careful next time to get more precise repro steps, but IIRC with NPM it's more of a 2-step process, where you can add or update something, but also need to do `npm install` to update the lockfile, whereas Yarn will add and update in one go. If you forget the second step with NPM, you can easily end up committing stuff without the lockfile changes. Also, Yarn just generally warns me more often when something's off.

**Comment by makinde** [comment]
Not sure if you're thinking of an npm workflow from years past, or if this is what you are experiencing today. In NPM 6, which is what comes with node 10, `npm i some-package` is the same as `yarn add some-package`. Both add the package to package.json and update the lock file. If you update `package.json` manually, you'll need to run `npm i` or `yarn install`. The gap that I can find is that there's no `yarn install --frozen-lockfile` (which is what majorkey runs in a precommit hook). Is that what's causing the issue?

**Pull request closed without merging**
